{
  "hash": "d0f5a2ef5ed1b84f3fc8bd9b4939ddc6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Desigualdade e expectativa de vida nos municípios (1991): MQO do zero\"\nsubtitle: \"Lista 1 · parte prática\"\ntipo: Lista\ndate: 2025-10-05\ndescription: \"Parte prática da lista 1: a esperança de vida ao nascer nos municípios brasileiros em 1991, explicada pela desigualdade da renda do trabalho (Gini). Uma regressão linear escrita do zero em R, comparada ao lm(), e o viés de variável omitida que inverte o sinal do Gini.\"\nimage: destaque.png\nimage-alt: \"Histogramas das variáveis contínuas do banco de municípios brasileiros de 1991.\"\nmetodos: [MQO matricial, Regressão múltipla, Viés de variável omitida]\ndados: [\"Municípios brasileiros (1991)\"]\nmateriais:\n  - {text: Enunciado, href: enunciado.pdf}\n  - {text: Soluções (PDF), href: solucoes.pdf}\n  - {text: Código, href: \"https://github.com/felipelmc/Lego-II/tree/main/trabalhos/lista-1\"}\nauthor: \"Felipe Lamarca\"\nformat:\n  pdf:\n    toc: false\n    number-sections: false\n    colorlinks: true\n    fig-pos: H\n    tbl-cap-location: top\n    fig-cap-location: top\n    df-print: kable\n    geometry:\n      - top=25mm\n      - left=20mm\n      - right=20mm\n      - bottom=25mm\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n::: {.callout-tip .achados}\n## Principais resultados\n- A função de MQO escrita do zero, com $\\hat{\\beta} = (X^\\top X)^{-1} X^\\top y$, reproduz os coeficientes e os erros-padrão do `lm()`.\n- Sozinho, o Gini da renda do trabalho aparece associado a mais esperança de vida: 9,95 anos a mais por unidade (de 0 a 1), com $R^2$ de apenas 0,02, um resultado que o relatório atribui a viés de variável omitida.\n- Controlando pela renda domiciliar per capita média, o sinal se inverte (0,05 ano a menos por ponto do Gini, na escala de 0 a 100). Com todas as covariáveis e as regiões, o $R^2$ chega a 0,68.\n:::\n\nAgora, passemos à parte prática da lista, na qual desenvolveremos algumas análises em `R` utilizando um banco de dados com informações a respeito dos municípios brasileiros em 1991, como a expectativa de vida ao nascer, população do município, Índice de Gini etc. De saída, vamos começar importando as bibliotecas necessárias, organizando um setup e lendo o arquivo que será utilizado na análise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# importa as libs\nlibrary(tidyverse)\nlibrary(stargazer)\n\n# remove o uso de e^\noptions(scipen = 999)\n\n# leitura do arquivo\nexpectativaVida = read.csv(\"dados/dados_expectativaVida.csv\")\n```\n:::\n\n\nO _output_ do código abaixo é uma série de histogramas, uma para cada variável contínua do banco de dados sob análise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# seleciona apenas as variáveis contínuas\ndados_cont <- expectativaVida %>%\n  select(esperanc, populaca, ginitrab, renda_me,\n         escoa2_p, urbano_p, med1000, pop15a_f)\n\n# transforma em formato longo pro facet\ndados_long <- dados_cont %>%\n  pivot_longer(cols = everything(),\n               names_to = \"variavel\",\n               values_to = \"valor\")\n\n# plota todos os histogramas em facets\n  ggplot(dados_long, aes(x = valor)) +\n  geom_histogram(bins = 30, fill = \"steelblue\", color = \"white\") +\n  facet_wrap(~ variavel, scales = \"free\", ncol = 3) +\n  labs(title = \"Histogramas das variáveis contínuas\",\n       x = NULL, y = NULL) +\n  theme_bw(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=1800}\n:::\n:::\n\n\n\n\nHá alguns pontos que valem destaque. Em particular, está claro que a grande parte dos municípios brasileiros possui população (`populaca`) bem pequenas; além disso, boa parte também possui um baixo percentual de domicílios com esgotamento sanitário (`escoa2_p`). Vejamos na tabela abaixo algumas estatísticas descritivas para cada variável do banco: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tabela com as estatisticas descritivas\ndesc = data.frame(\n  variavel = names(expectativaVida),\n  media = sapply(\n    expectativaVida, \n    function(x) if (is.numeric(x)) mean(x, na.rm = TRUE) else NA_real_\n    ),\n  mediana = sapply(\n    expectativaVida, \n    function(x) if (is.numeric(x)) median(x, na.rm = TRUE) else NA_real_\n    ),\n  desvio_padrao = sapply(\n    expectativaVida, \n    function(x) if (is.numeric(x)) sd(x, na.rm = TRUE) else NA_real_\n    ),\n  n_validos = sapply(\n    expectativaVida, \n    function(x) sum(!is.na(x))\n    ),\n  row.names = NULL\n)\n\n# numero de linhas\nn = nrow(expectativaVida)\n\n# proporcao de linhas validas (acho util, em particular)\ndesc$prop_validos = (desc$n_validos / n) * 100\n\n# plot bonitinho da tabela\nstargazer(\n  desc,\n  type = \"text\",\n  summary = FALSE,\n  title = \"Estatísticas Descritivas\",\n  digits = 2,\n  rownames = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstatísticas Descritivas\n===============================================================\nvariavel   media   mediana desvio_padrao n_validos prop_validos\n---------------------------------------------------------------\nesperanc   63.63    64.05      5.08        4,491       100     \npopulaca 32,693.27 12,407   187,705.20     4,491       100     \nginitrab   0.52     0.52       0.07        4,491       100     \nrenda_me  274.29   238.57     164.68       4,491       100     \nescoa2_p   25.42    11.68      28.52       4,491       100     \nurbano_p   53.14    51.67      23.26       4,491       100     \nmed1000    0.60     0.44       0.55        4,332      96.46    \nnorte      0.07       0        0.25        4,491       100     \ncentrooe   0.08       0        0.28        4,491       100     \nsul        0.19       0        0.40        4,491       100     \nnordeste   0.34       0        0.47        4,491       100     \npop15a_f   15.14    14.08      7.96        4,491       100     \n---------------------------------------------------------------\n```\n\n\n:::\n:::\n\nDe fato, como já havíamos observado no histograma da variável `populaca`, os municípios têm, em geral, pequena população. Note, por exemplo, que 50% dos municípios possui população menor que 12.407 habitantes; há, no entanto, municípios com alta população, o que se reflete no desvio padrão. A esperança de vida ao nascer, nossa variável resposta para os exercícios subsequentes, tinha média 63.63 naquele ano. A coluna `prop_validos` também nos ajuda a compreender o percentual de observações daquela coluna que possuem valor _missing_. \n\nAgora vamos rodar as regressões! Para ajustar alguns dos modelos a seguir, vamos implementar uma função de regressão linear _from scratch_ em `R`. A função retorna os coeficientes da regressão (i.e. o vetor $\\beta$), os erros-padrão desses coeficientes, seus p-valores, e algumas estatísticas próprias do modelo, como o $\\text{R}^2$, a variância dos resíduos e seu desvio-padrão (`RMSE`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_model = function(formula, data = expectativaVida) {\n  \n  dependent_variable = as.character(formula[[2]])\n  \n  X = model.matrix(formula, data = data)\n  y = data[[dependent_variable]]\n  \n  # beta estimado: \\hat{\\beta} = (X^T X)^{-1} X^T y\n  beta_hat = solve( t(X) %*% X ) %*% t(X) %*% y\n  \n  # y estimado a partir do modelo: \\hat{y} = X \\hat{\\beta} \n  y_hat = X %*% beta_hat\n  \n  # residuals sao a diferenca entre y 'verdadeiro' e y estimado\n  residuals = y - y_hat\n  \n  n = nrow(X)\n  k = ncol(X)\n  \n  # erro quadratico medio\n  var_residuals = sum(residuals^2) / (n - k)\n  \n  # raiz do erro quadratico medio\n  RMSE = sqrt(var_residuals)\n  \n  # R-squared, ou proporcao da variancia explicada pelo modelo\n  total_variance = var(y)\n  R2 = 1 - var_residuals / total_variance\n  \n  # sob homocedasticidade (ML.5), var(\\beta) = \\sigma^2 (X^T X)^{-1}\n  # onde a equivalencia de \\sigma^2 para a amostra é a variância dos residuos\n  varcov_beta_hat = var_residuals * solve( t(X) %*% X )\n  se_beta_hat = sqrt(diag(varcov_beta_hat))\n  \n  # teste de hipotese para o p-valor \n  H0 = 0 # teste contra a H0 de o efeito ser nulo\n  t = (beta_hat - H0) / se_beta_hat\n  p_valor = 2 * (1 - pnorm(abs(t)))\n  \n  coefs <- data.frame(\n    Coeficientes = colnames(X),\n    Estimativas = round(as.numeric(beta_hat), 4),\n    Erros_padrao = round(se_beta_hat, 4),\n    t = t,\n    p_valor = p_valor,\n    row.names = NULL,\n    check.names = FALSE\n  )\n  \n  list(\n    coefs = coefs,\n    R2 = R2,\n    RMSE = RMSE,\n    var_residuals = var_residuals\n  )\n}\n```\n:::\n\n\nA primeira regressão ajustada inclui apenas a variável de desigualdade de renda como variável explicativa (`genitrab`) da esperança de vida ao nascer. Vejamos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(linear_model(formula = esperanc ~ ginitrab))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coefs\n  Coeficientes Estimativas Erros_padrao          t p_valor\n1  (Intercept)     58.4775       0.5485 106.606577       0\n2     ginitrab      9.9553       1.0509   9.473201       0\n\n$R2\n[1] 0.01938121\n\n$RMSE\n[1] 5.030641\n\n$var_residuals\n[1] 25.30735\n```\n\n\n:::\n:::\n\nVale a pena testar se nossos resultados são idênticos aos obtidos quando usamos a função nativa do `R` para ajustar modelos lineares, `lm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(\n  lm(\n    formula = esperanc ~ ginitrab, \n    data = expectativaVida\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = esperanc ~ ginitrab, data = expectativaVida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.9188  -3.8036   0.3425   3.9275  11.8394 \n\nCoefficients:\n            Estimate Std. Error t value            Pr(>|t|)    \n(Intercept)  58.4775     0.5485 106.607 <0.0000000000000002 ***\nginitrab      9.9553     1.0509   9.473 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.031 on 4489 degrees of freedom\nMultiple R-squared:  0.0196,\tAdjusted R-squared:  0.01938 \nF-statistic: 89.74 on 1 and 4489 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\nSão idênticos, felizmente! Podemos interpretar nossos resultados com tranquilidade. \n\nO intercepto é o valor da variável dependente quando as variáveis independentes são zero. Nesse caso, portanto, dizemos que, quando `ginitrab` é zero -- isto é, não há desigualdade de renda do trabalho --, a expectativa de vida ao nascer é 58.5, em média. $\\beta_1$, o coeficiente para `ginitrab`, indica que para o aumento em uma unidade de `ginitrab`, a expectativa de vida cresce em 9.95 anos. Esse resultado deveria ser estranho a qualquer cientista: estamos dizendo, em essência, que o aumento da desigualdade leva a um aumento na expectativa de vida. Trata-se, muito provavelmente, de um viés de variável omitida, mas voltaremos a essa questão oportunamente.\n\nOs erros-padrão dos coeficientes são pequenos, o que nos leva a p-valores baixos, muito próximos de zero. Os efeitos, portanto, são estatisticamente significativos. O R-squared é baixo, então a variância explicada pelo modelo é pequena -- ou seja, `ginitrab` sozinho explica pouco da variabilidade da variável resposta. Além disso, o erro médio das previsões é de 5 anos, conforme o valor do RMSE.\n\nAgora, façamos uma pequena modificação na variável explicativa, multiplicando-a por 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpectativaVida = expectativaVida %>%\n  mutate(\n    ginitrab100 = ginitrab * 100\n  )\n\nreg1 = lm(formula = esperanc ~ ginitrab100, data = expectativaVida)\n\nsummary(reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = esperanc ~ ginitrab100, data = expectativaVida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.9188  -3.8036   0.3425   3.9275  11.8394 \n\nCoefficients:\n            Estimate Std. Error t value            Pr(>|t|)    \n(Intercept) 58.47755    0.54854 106.607 <0.0000000000000002 ***\nginitrab100  0.09955    0.01051   9.473 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.031 on 4489 degrees of freedom\nMultiple R-squared:  0.0196,\tAdjusted R-squared:  0.01938 \nF-statistic: 89.74 on 1 and 4489 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\nA multiplicação não muda nada do ponto de vista estatístico, embora possa facilitar a interpretação dos resultados em certos casos. No caso em que não fizemos a multiplicação por 100, dizíamos que, aumentando `ginitrab` em uma unidade, aumentávamos a expectativa de vida em mais de 9 anos. Mas como `ginitrab` era uma variável contínua entre 0 e 1, estávamos indo de um cenário extremo para outro (de 0 para 1). Quando multiplicamos por 100, podemos dizer que o aumento em uma unidade do Índice de Gini leva a um incremento da expectativa de vida em 0.099 ano. Isso ainda não faz sentido do ponto de vista qualitativo, é claro, mas deixa a interpretação do coeficiente mais informativa.\n\nAgora vamos lidar com o problema do viés de variável omitida. Em particular, vamos incluir a renda domiciliar per capita média como variável explicativa e analisar os coeficientes. Primeiro, vamos ajustar um modelo usando a função que criamos _from scratch_:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg2_mine = linear_model(formula = esperanc ~ ginitrab100 + renda_me)\nprint(reg2_mine)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$coefs\n  Coeficientes Estimativas Erros_padrao          t              p_valor\n1  (Intercept)     60.5965       0.4036 150.152844 0.000000000000000000\n2  ginitrab100     -0.0574       0.0081  -7.081885 0.000000000001421974\n3     renda_me      0.0219       0.0004  62.168859 0.000000000000000000\n\n$R2\n[1] 0.4730019\n\n$RMSE\n[1] 3.687888\n\n$var_residuals\n[1] 13.60052\n```\n\n\n:::\n:::\n\nVamos checar se o resultado é o mesmo quando usamos `lm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg2 = lm(formula = esperanc ~ ginitrab100 + renda_me, data = expectativaVida)\nsummary(reg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = esperanc ~ ginitrab100 + renda_me, data = expectativaVida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.1536  -2.5072   0.1249   2.6296  10.0669 \n\nCoefficients:\n              Estimate Std. Error t value             Pr(>|t|)    \n(Intercept) 60.5965070  0.4035655 150.153 < 0.0000000000000002 ***\nginitrab100 -0.0574135  0.0081071  -7.082     0.00000000000164 ***\nrenda_me     0.0218646  0.0003517  62.169 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.688 on 4488 degrees of freedom\nMultiple R-squared:  0.4732,\tAdjusted R-squared:  0.473 \nF-statistic:  2016 on 2 and 4488 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\nTudo certo! Vejamos os resultados, então. Agora, finalmente, temos um coeficiente para `ginitrab100` que faz mais sentido (dessa vez, negativo). Quando aumentamos o Índice de Gini em uma unidade e mantemos o resto fixo, a expectativa de vida ao nascer decresce, em média, em 0.05 ano. Além disso, para uma unidade que incrementamos na renda per capita média do município -- mantendo o resto fixo --, a expectativa de vida ao nascer cresce em 0.02 ano. Todos os coeficientes são estatisticamente significativos e possuem baixo erro-padrão. Além disso, o R-squared é substantivamente melhor do que o observado no primeiro modelo.\n\nA interpretação do coeficiente para `ginitrab100` é diferente porque, antes, não controlávamos por outras variáveis que afetavam tanto a expectativa de vida quanto `ginitrab100`, como a renda per capita média. Nesse caso, havia pelo menos uma variável confundidora, `renda_me`, que enviesava a estimativa do beta para `ginitrab100`. \n\nVamos incluir mais variáveis no modelo para verificar como os resultados se comportam. Dessa vez, vamos incluir `log(populaca)`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3 = lm(\n  formula = esperanc ~ ginitrab100 + renda_me + log(populaca), \n  data = expectativaVida\n  )\n\nsummary(reg3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = esperanc ~ ginitrab100 + renda_me + log(populaca), \n    data = expectativaVida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-29.5079  -2.2982   0.1263   2.5502  10.2874 \n\nCoefficients:\n                Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)   68.9810535  0.5866102 117.593 < 0.0000000000000002 ***\nginitrab100   -0.0447944  0.0078263  -5.724         0.0000000111 ***\nrenda_me       0.0235496  0.0003497  67.351 < 0.0000000000000002 ***\nlog(populaca) -0.9984062  0.0523691 -19.065 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.547 on 4487 degrees of freedom\nMultiple R-squared:  0.5127,\tAdjusted R-squared:  0.5124 \nF-statistic:  1574 on 3 and 4487 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\nAo incluir `log(populaca)`, as estimativas dos betas para `ginitrab100` e `renda_me` não se alteraram grosseiramente. Os coeficientes são todos estatisticamente significativos, e tivemos um ganho não-ignorável no R-squared. Ao incluir a variável da população na escala logarítmica, estamos comprimindo a escala dessa variável para evitar que o modelo seja muito sensível à alta variância dessa covaríavel. Vimos entre as estatísticas descritivas, por exemplo, que o desvio-padrão da população dos municípios é altíssima.\n\nPara interpretar o coeficiente de `log(populaca)`, precisamos levar em consideração algumas propriedades do logaritmo. Em particular, devemos usar a seguinte aproximação, conforme demonstrado em...\n\n$$\n\\log (X_\\text{final}) - \\log (X_\\text{inicial}) = \\log \\left( \\dfrac{X_\\text{final}}{X_\\text{inicial}} \\right) \\approx \\log \\left( \\dfrac{X_\\text{final} - X_\\text{inicial}}{X_\\text{inicial}} \\right) = \\log \\left( \\dfrac{\\Delta X}{X_\\text{inicial}} \\right),\n$$\npresumindo que $\\Delta X$ é suficientemente pequeno. Dito de outro modo, podemos interpretar o coeficiente da variável na escala log em termos de variação percentual. Portanto, a cada uma unidade de `log(populaca)` que aumentamos a população em 1%, controlando pelas demais variáveis, diminuímos a expectativa de vida ao nascer em aproximadamente 0.0099 ano, em média.\n\nPor fim, vamos ajustar um modelo com todas as covariáveis disponíveis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformula_ = esperanc ~ ginitrab100 + renda_me + log(populaca) + escoa2_p +\n  urbano_p + med1000 + pop15a_f + norte + centrooe + sul + nordeste\n\nreg4 = lm(\n  formula = formula_, \n  data = expectativaVida\n  )\n\nsummary(reg4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = formula_, data = expectativaVida)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.1851 -1.9687  0.1669  2.1229  9.1558 \n\nCoefficients:\n                Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)   67.6369495  0.5171727 130.782 < 0.0000000000000002 ***\nginitrab100   -0.0294642  0.0067134  -4.389  0.00001166656782483 ***\nrenda_me       0.0081743  0.0005242  15.595 < 0.0000000000000002 ***\nlog(populaca) -0.4789586  0.0505342  -9.478 < 0.0000000000000002 ***\nescoa2_p       0.0212725  0.0025488   8.346 < 0.0000000000000002 ***\nurbano_p      -0.0239271  0.0029920  -7.997  0.00000000000000162 ***\nmed1000       -0.1784613  0.0947582  -1.883               0.0597 .  \npop15a_f       0.1467231  0.0115450  12.709 < 0.0000000000000002 ***\nnorte         -2.1534272  0.2196830  -9.802 < 0.0000000000000002 ***\ncentrooe      -1.2653372  0.1969555  -6.424  0.00000000014662483 ***\nsul            1.1204752  0.1410866   7.942  0.00000000000000252 ***\nnordeste      -4.5303204  0.1503863 -30.125 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.879 on 4320 degrees of freedom\n  (159 observations deleted due to missingness)\nMultiple R-squared:  0.6785,\tAdjusted R-squared:  0.6777 \nF-statistic:   829 on 11 and 4320 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\nOs ganhos são claros: temos um R-squared de 0.68, e praticamente todos os coeficientes são estatisticamente significativos, com exceção de `med1000`. O coeficiente da renda per capita média do município perdeu magnitude, um resultado provavelmente resultante da correlação entre essa variável e as demais variáveis do modelo. Quando as demais variáveis não eram incluídas, `renda_me` assumia parte desses efeitos. Algo semelhante ocorreu, inclusive, com a variável `log(populaca)`. \n\nObserve também as variáveis categóricas do modelo. Note, em particular, que não foi incluída a variável `sudeste`, que de fato sequer existia no banco de dados. Como discutimos na parte conceitual desta lista, a inclusão da variável `sudeste` introduziria colinearidade perfeita no modelo e impediria o cálculo dos coeficientes. A consequência, aqui, é que Sudeste é a categoria de base. Do ponto de vista interpretativo, observamos que o fato de o município fazer parte da região Sul está, em média, associado a maiores expectativas de vida ao nascer do que no Sudeste; observamos o contrário, no entanto, para as regiões Centro-Oeste, Norte e sobretudo Nordeste.\n\nA tabela abaixo sistematiza os resultados de todos os modelos ajustados em uma única tabela para facilitar a visualização dos resultados. Outra alternativa seria apresentar os coeficientes graficamente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstargazer(reg1, reg2, reg3, reg4,\n          type = \"text\",\n          title = \"Modelos de Regressão Linear ajustados\",\n          dep.var.labels = \"Esperança de Vida\",\n          column.labels = c(\"Modelo 1\", \"Modelo 2\", \"Modelo 3\", \"Modelo 4\"),\n          digits = 3,\n          omit.stat = c(\"f\", \"adj.rsq\", \"ll\", \"aic\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModelos de Regressão Linear ajustados\n===========================================================================================\n                                              Dependent variable:                          \n                    -----------------------------------------------------------------------\n                                               Esperança de Vida                           \n                        Modelo 1          Modelo 2          Modelo 3          Modelo 4     \n                           (1)               (2)               (3)               (4)       \n-------------------------------------------------------------------------------------------\nginitrab100             0.100***          -0.057***         -0.045***         -0.029***    \n                         (0.011)           (0.008)           (0.008)           (0.007)     \n                                                                                           \nrenda_me                                  0.022***          0.024***          0.008***     \n                                          (0.0004)          (0.0003)           (0.001)     \n                                                                                           \nlog(populaca)                                               -0.998***         -0.479***    \n                                                             (0.052)           (0.051)     \n                                                                                           \nescoa2_p                                                                      0.021***     \n                                                                               (0.003)     \n                                                                                           \nurbano_p                                                                      -0.024***    \n                                                                               (0.003)     \n                                                                                           \nmed1000                                                                        -0.178*     \n                                                                               (0.095)     \n                                                                                           \npop15a_f                                                                      0.147***     \n                                                                               (0.012)     \n                                                                                           \nnorte                                                                         -2.153***    \n                                                                               (0.220)     \n                                                                                           \ncentrooe                                                                      -1.265***    \n                                                                               (0.197)     \n                                                                                           \nsul                                                                           1.120***     \n                                                                               (0.141)     \n                                                                                           \nnordeste                                                                      -4.530***    \n                                                                               (0.150)     \n                                                                                           \nConstant                58.478***         60.597***         68.981***         67.637***    \n                         (0.549)           (0.404)           (0.587)           (0.517)     \n                                                                                           \n-------------------------------------------------------------------------------------------\nObservations              4,491             4,491             4,491             4,332      \nR2                        0.020             0.473             0.513             0.679      \nResidual Std. Error 5.031 (df = 4489) 3.688 (df = 4488) 3.547 (df = 4487) 2.879 (df = 4320)\n===========================================================================================\nNote:                                                           *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\nPor fim, um último comentário: embora o modelo 4 inclua uma série de covariáveis importantes que nos ajudam a compreender o comportamento da expectativa de vida, ele ainda não tem interpretação causal. De fato, estamos controlando por uma série de variáveis, mas não por todas; certamente há outros fatores que afetam não apenas a variável de interesse, como também as variáveis independentes -- isso inclui, por exemplo, questões associadas à política local, repasses financeiros do governo federal e governos estaduais para os municípios, fatores conjunturais e assim por diante. Isso não altera o fato, no entanto, de que o modelo 4 está mais próximo de oferecer uma explicação causal do que o modelo 1.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}